### ISSUE TITLE
The gree platform for the climate integration does not support platform setup. Please remove it from your config

### ISSUE THREAD

**Issue by hengike** [RobHofmann/HomeAssistant-GreeClimateComponent#104]
Just tried out so It's really possible that I messed up something.

1. Started up an empty dockerized core container.
2. Copy the YML file add the IP and MAC address
3. Delete the optional lines
4. Restart the container
5. Check the log
6. **The gree platform for the climate integration does not support platform setup. Please remove it from your config**
`- platform: gree
  name: First AC
  host: <first_ac_ip>
  port: 7000
  mac: <first_ac_mac>
  target_temp_step: 1

- platform: gree
  name: Second AC
  host: <second_ac_ip>
  port: 7000
  mac: <second_ac_mac>
  target_temp_step: 1`

**Platform:**
 - Browser chrome
**Logs**
`2021-07-06 18:53:59 INFO (MainThread) [greeclimate.discovery] Scanning for Gree devices ...
2021-07-06 18:53:59 DEBUG (MainThread) [greeclimate.discovery] Listening for devices on 192.168.50.120
2021-07-06 18:53:59 DEBUG (MainThread) [greeclimate.discovery] Listening for devices on 172.18.0.1
2021-07-06 18:53:59 DEBUG (MainThread) [greeclimate.discovery] Listening for devices on 172.17.0.1
2021-07-06 18:53:59 DEBUG (MainThread) [greeclimate.network] Sending packet:
2021-07-06 18:53:59 DEBUG (MainThread) [greeclimate.network] Sending packet:
2021-07-06 18:53:59 DEBUG (MainThread) [greeclimate.network] Sending packet:
2021-07-06 19:07:13 INFO (SyncWorker_3) [homeassistant.loader] Loaded gree from homeassistant.components.gree
2021-07-06 19:07:13 ERROR (MainThread) [homeassistant.components.climate] The gree platform for the climate integration does not support platform setup. Please remove it from your config.
2021-07-06 19:07:13 ERROR (MainThread) [homeassistant.components.climate] The gree platform for the climate integration does not support platform setup. Please remove it from your config.
`

**Comment by ronnicek** [comment]
I have same issue :-/

And when I try to search it via "Add integration" I just get following error:
```
homeassistant    | 2021-07-20 22:01:00 ERROR (MainThread) [aiohttp.server] Error handling request
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
homeassistant    |     resp = await self._request_handler(request)
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
homeassistant    |     resp = await handler(request)
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
homeassistant    |     return await handler(request)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
homeassistant    |     result = await result
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
homeassistant    |     return await super().post(request, flow_id)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
homeassistant    |     result = await method(view, request, *args, **kwargs)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
homeassistant    |     result = await self._flow_mgr.async_configure(flow_id, data)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
homeassistant    |     result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
homeassistant    |     result: FlowResult = await getattr(flow, method)(user_input)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/helpers/config_entry_flow.py", line 58, in async_step_confirm
homeassistant    |     has_devices = await self.hass.async_add_job(  # type: ignore
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/gree/config_flow.py", line 12, in _async_has_devices
homeassistant    |     devices = await gree_discovery.scan(wait_for=DISCOVERY_TIMEOUT)
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/greeclimate/discovery.py", line 162, in scan
homeassistant    |     await self.search_devices()
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/greeclimate/discovery.py", line 210, in search_devices
homeassistant    |     await asyncio.gather(
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/greeclimate/discovery.py", line 202, in search_on_interface
homeassistant    |     await self.send({"t": "scan"}, (bcast_iface.bcast_address, 7000))
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/greeclimate/network.py", line 122, in send
homeassistant    |     self._transport.sendto(data_bytes, addr)
homeassistant    |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1061, in sendto
homeassistant    |     self._protocol.error_received(exc)
homeassistant    |   File "/usr/local/lib/python3.9/site-packages/greeclimate/network.py", line 86, in error_received
homeassistant    |     raise exc
homeassistant    |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
homeassistant    |     self._sock.sendto(data, addr)
homeassistant    | PermissionError: [Errno 1] Operation not permitted
```

**Comment by ronnicek** [comment]
Found the issue.. You really need to move `custom_components` from git repo to `config` folder. Looks like gree integration in HA is not the same as here. Then the configuration in `climate.yaml` is working well.

**Comment by RobHofmann** [comment]
Yes, you guys are just using the default `gree` component by Home Assistant itself. You can install this custom component through HACS, or copy it to your `custom_components` folder yourself. But without this step, you are not using this component but the default one :).

Closing this one for now.
