### ISSUE TITLE
Addon is not work

### ISSUE THREAD

**Issue by quas1k** [RobHofmann/HomeAssistant-GreeClimateComponent#111]
**Describe the bug**
Addon is not work for my device Cooper&Hunter CH-S12FTXN-PW

**Configuration**
climate:
    - platform: gree
      name: First AC
      host: 192.168.31.39
      port: 7000
      mac: 18:69:D8:C6:D2:06
      target_temp_step: 1

**Platform:**
 - OS: HASSIO
 - Browser chrome

**Logs**
`Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 118, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, eightdegheat_entity_id, air_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/config/custom_components/gree/climate.py", line 165, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/config/custom_components/gree/climate.py", line 249, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/config/custom_components/gree/climate.py", line 232, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out`

**Comment by quas1k** [comment]
Sorry
My device: Cooper&Hunter Nordic Evo NG CH-S12FTXN-NG

**Comment by RobHofmann** [comment]
This is a generic timeout. This means your device can't be reached from HomeAssistant. Make sure they can reach eachother & your wifi is enabled :).
