### ISSUE TITLE
Cannot connect to Gree GWH18AAD-K6DNA1D

### ISSUE THREAD

**Issue by damonmaria** [RobHofmann/HomeAssistant-GreeClimateComponent#115]
**Describe the bug**
Trying to use this with a Gree GWH18AAD-K6DNA1D, and having no luck. I can successfully control the AC using the GREE+ Android app  but installing this component I always get: "No devices found on the network".

I know the AC's IP address but using both `nc` and `nmap` I can't find any open ports on it. I am presuming it's TCP. I gather from the README port 7000 should be open. 

I am a developer by trade and have network skills (but am a HA newbie) so I'm happy to try anything you suggest. 

The following was in the log but I don't know if this relates to this component trying to find the AC unit:
```
2021-12-11 14:31:27 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 485, in start
resp, reset = await task
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
reset = await self.finish_response(request, resp, start_time)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
await prepare_meth(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 241, in prepare
return await self._sendfile(request, fobj, offset, count)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 96, in _sendfile
await loop.sendfile(transport, fobj, offset, count)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1151, in sendfile
return await self._sendfile_native(transport, file,
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 586, in _sendfile_native
return await self.sock_sendfile(transp._sock, file, offset, count,
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 867, in sock_sendfile
self._check_sendfile_params(sock, file, offset, count)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 920, in _check_sendfile_params
raise ValueError(
ValueError: count must be a positive integer (got 0)
```

I also attempted to add the configuration manually as per the README but I get the following:
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:164
Integration: Climate (documentation, issues)
First occurred: 2:17:38 PM (1 occurrences)
Last logged: 2:17:38 PM

The gree platform for the climate integration does not support platform setup. Please remove it from your config.
```

**Platform:**
 - OS: Home Assistant OS 6.6
 - Browser Chrome
 - Version: core-2021.11.5

**Comment by RobHofmann** [comment]
Seems your model is unsupported due to a custom gree protocol. Feel free to create a PR where support is added.
