### ISSUE TITLE
Unavailable device

### ISSUE THREAD

**Issue by MrSimpa** [RobHofmann/HomeAssistant-GreeClimateComponent#123]
My Gree climate entity is Unavailable, if i restart HA a few times its start working, but i must restart it 3-5 times. I can control if with my phone (iOS) all time.

![image](https://user-images.githubusercontent.com/70363270/163166549-94a834f3-b16d-45c6-8246-58ce927b7363.png)

Configuration:
climate:
    - platform: gree
      name: Klima
      host: 192.168.1.55
      port: 7000
      mac: '50:2C:C6:6D:C5:8A'
      target_temp_step: 1
      xfan: input_boolean.klima_ac_xfan
      lights: input_boolean.klima_lights
      sleep: input_boolean.klima_sleep
      health: input_boolean.klima_health
      powersave: input_boolean.klima_powersave
          
input_boolean:
  klima_ac_xfan:
    name: Klima XFan
    initial: off
  klima_lights:
    name: Klima lights
    initial: off
  klima_sleep:
    name: Klima sleep mode
    initial: off
  klima_health:
    name: Klima healthy mode
    initial: off
  klima_powersave:
    name: Klima powersave mode
    initial: off 

Log: 
**Logger: homeassistant.components.climate
Source: custom_components/gree/climate.py:230
Integration: Climate (documentation, issues)
First occurred: April 12, 2022, 20:22:08 (1 occurrences)
Last logged: April 12, 2022, 20:22:08

Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 116, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, eightdegheat_entity_id, air_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/config/custom_components/gree/climate.py", line 163, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/config/custom_components/gree/climate.py", line 247, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/config/custom_components/gree/climate.py", line 230, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out**

**Comment by Stealthii** [comment]
Duplicate of #117
