### ISSUE TITLE
Error adding entities for domain climate with platform gree

### ISSUE THREAD

**Issue by jodewee** [RobHofmann/HomeAssistant-GreeClimateComponent#125]
config in climate.yaml:
- platform: gree
  name: Airco Lander
  host: 192.168.2.37
  port: 7000
  mac: '50:2c:c6:3f:eb:0d'
  encryption_key: '6p1e6T0I5XeMtAiP'
  target_temp_step: 1

- platform: gree
  name: Airco 1
  host: 192.168.2.89
  port: 7000
  mac: '50:2c:c6:6c:d3:63'
  encryption_key: 'sAhP4E9T4I0X5M0b'
  target_temp_step: 1

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 807, in async_added_to_hass
    self.SyncState()
  File "/config/custom_components/gree/climate.py", line 434, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/config/custom_components/gree/climate.py", line 251, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/config/custom_components/gree/climate.py", line 230, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
2022-05-19 09:50:09 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform gree

data captured:
定时查询状态 to  Lan IP:192.168.2.37 port:7000 data:{"cid":"app","i":0,"pack":"odgfEsRE+0zGKB2PlaCdtXLH4nbHOoOckqaW7C7VqifDuag6WPlkGNbDXCIzUerBUJPM8oekAsaZBxeSQlQy0R3Glx5e6BoqbkaN35pMX77/fjfILKKAYtaMwUOA2QH69jB/8R2yRZ3WfG2P7IeElK6awqcBIU3rh9sHiHl3wsVI2uJ3d0On8IpAdC6BYHwPxLTkljc+l27/SVjbbk4v38W6UKo=","t":"pack","tag":"oykZ3UPZE4WWQUx/JH1+Gw==","tcid":"502cc63feb0d","uid":2304849}
05-16 11:54:01.329  6820  7161 I GR_DeviceManage: 接收数据：{"t":"pack","i":0,"uid":0,"cid":"502cc63feb0d","tcid":"","tag":"TUEYEhaDttKKZhCFb94usA==","pack":"odgIX5IVvRfpKGHCj+PStQCAtjK2No/G9bmD6zydqkaOr6gsSJ0xWaHOEWJiILXuJqbOp4mqdOuRNAayDxd81hD+hh5e6AQzWRCD0exBXZjlfjfIEaaZU5HNwS7O4SHl1ncw8Xz/cozyXDbTq/be5ZvIntEAI1vth9sHonV1w8U51IF2emX3uIpZZlGNZy9Q9qj2w3EwmQ37GzaQcF88iZzrNroJUqw+xJFHKCjRYE2cgAUF3SYETIjdCCtcHrlNZVKhwtTo++s4vrT/qY2fgmdLZO6OZl1pzkMREBOao4pXrM//feh7CwMU3w=="}   Ip:192.168.2.37  port:7000
05-16 11:54:01.330  6820  7161 D GR_DeviceManage: 192.168.2.37prase status pack:{"t":"dat","mac":"502cc63feb0d","r":200,"cols":["Pow","HeatCoolType","Mod","TemUn","SetTem","TemRec","StHt","SvSt","host","name","AllErr","ModelType","AppTimer","Dmod"],"dat":[0,0,1,0,19,0,0,0,"eu.dis.gree.com","c63feb0d",0,32776,0,0]}
05-16 11:54:01.426  6820 11923 D GR_DeviceManage: is Remote=true count:2

**Comment by Bambek** [comment]
mam ten sam problem... jakieś rozwiązanie?

**Comment by jodewee** [comment]
> I have the same problem ... any solution?

no, still not found any working config

**Comment by RobHofmann** [comment]
The error tells us it can not reach the HVAC. Your model might not be supporting gree on port 7000.
