### ISSUE TITLE
"Error while setting up platform gree" (Home Assistant on Raspbian)

### ISSUE THREAD

**Issue by sarimabbas** [RobHofmann/HomeAssistant-GreeClimateComponent#13]
Hi, and thank you for your work on this component. I was hoping you could help shed some light on why the set up for the component may be failing:

```
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] Fetching Device Encryption Key
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] GetDeviceKey()
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] Creating encryptor with Device Key
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] Encrypting Pack
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] Creating JSON
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] Fetching & Returning result
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] FetchResult(<192.168.86.140>, 7000, {"cid": "app","i": 1,"pack": "nCSrGV4L+TyuYwrmhZH6mkkLd5OEPeolO6mwrilXgbWj9mrs/0p7GUTdWxmNaBUt","t":"pack","tcid":"f4911e69d75c","uid": 0})
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] Creating sock
2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] Sending over UDP
2019-05-15 07:15:30 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform gree
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 113, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, min_temp, max_temp, target_temp, target_temp_step, temp_sensor_entity_id, operation_list, fan_list, swing_updn_mode_list, default_operation, default_fan_mode, default_operation_from_idle, default_swing_updn_mode, encryption_key, uid)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 152, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 220, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, jsonPayloadToSend)['key']
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 188, in FetchResult
    clientSock.sendto(bytes(json, "utf-8"), (ip_addr, port))
socket.gaierror: [Errno -2] Name or service not known
2019-05-15 07:15:41 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry UPnP/IGD for upnp
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/async_upnp_client/aiohttp.py", line 103, in async_do_http_request
    async with self._session.request(method, url, headers=headers, data=body) as response:
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 729, in create_connection
    yield from tasks.wait(fs, loop=self)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 355, in wait
    return (yield from _wait(fs, timeout, return_when, loop))
  File "/usr/lib/python3.5/asyncio/tasks.py", line 438, in _wait
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
concurrent.futures._base.CancelledError
```

I'm not sure what the problem might be. I did not specify an encryption key in the .yaml file though. Could this be the problem? Unfortunately I do not have an Android device to recover the SQLite db. Are there any alternative solutions for iOS? Many thanks.

**Comment by RobHofmann** [comment]
Can you share your config? It looks like you forgot to delete the less-than-sign and the greater-than-sign on the IP.

If you look at this log: 2019-05-15 07:15:28 INFO (MainThread) [custom_components.gree.climate] FetchResult(<192.168.86.140>, 7000, {"cid": "app","i": 1,"pack": "nCSrGV4L+TyuYwrmhZH6mkkLd5OEPeolO6mwrilXgbWj9mrs/0p7GUTdWxmNaBUt","t":"pack","tcid":"f4911e69d75c","uid": 0})

you see that the IP still has the < and the > around it. Remove this from the config and it should be good to go.

**Comment by sarimabbas** [comment]
Thanks for your help! It's getting further along now. However, it is now encountering a familiar error:

```
pi@raspberrypi:/home/homeassistant/.homeassistant $ cat home-assistant.log
2019-05-19 04:36:16 INFO (MainThread) [custom_components.gree.climate] Fetching Device Encryption Key
2019-05-19 04:36:16 INFO (MainThread) [custom_components.gree.climate] GetDeviceKey()
2019-05-19 04:36:16 INFO (MainThread) [custom_components.gree.climate] Creating encryptor with Device Key
2019-05-19 04:36:17 INFO (MainThread) [custom_components.gree.climate] Encrypting Pack
2019-05-19 04:36:17 INFO (MainThread) [custom_components.gree.climate] Creating JSON
2019-05-19 04:36:17 INFO (MainThread) [custom_components.gree.climate] Fetching & Returning result
2019-05-19 04:36:17 INFO (MainThread) [custom_components.gree.climate] FetchResult(192.168.86.140, 7000, {"cid": "app","i": 1,"pack": "nCSrGV4L+TyuYwrmhZH6mkkLd5OEPeolO6mwrilXgbWj9mrs/0p7GUTdWxmNaBUt","t":"pack","tcid":"f4911e69d75c","uid": 0})
2019-05-19 04:36:17 INFO (MainThread) [custom_components.gree.climate] Creating sock
2019-05-19 04:36:17 INFO (MainThread) [custom_components.gree.climate] Sending over UDP
2019-05-19 04:36:17 INFO (MainThread) [custom_components.gree.climate] Receiving over UDP
2019-05-19 04:36:17 INFO (MainThread) [custom_components.gree.climate] Loading received JSON
2019-05-19 04:36:18 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform gree
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 113, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, min_temp, max_temp, target_temp, target_temp_step, temp_sensor_entity_id, operation_list, fan_list, swing_updn_mode_list, default_operation, default_fan_mode, default_operation_from_idle, default_swing_updn_mode, encryption_key, uid)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 152, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 220, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, jsonPayloadToSend)['key']
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 192, in FetchResult
    receivedJson = simplejson.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I looked at the previous issues, and double-checked to make sure I have `simplejson` installed:

```
pi@raspberrypi:/home/homeassistant/.homeassistant $ pip3 freeze | grep "simple*"
simplejson==3.10.0
pi@raspberrypi:/home/homeassistant/.homeassistant $ pip freeze | grep "simple*"
simplejson==3.16.0
```

Would you know why this might be happening? Thanks so much again for your help.

**Comment by RobHofmann** [comment]
Can you try the suggestion from this post: https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/10#issuecomment-492532172

This might work. As described; i dont have a way to test this myself.

**Comment by RobHofmann** [comment]
Going to close this for now. Reopen this issue if needed.
