### ISSUE TITLE
Integracion with Home Assistant

### ISSUE THREAD

**Issue by bertocea85** [RobHofmann/HomeAssistant-GreeClimateComponent#132]
**Describe the bug**
From home assist I send an action on/off, temperature, etc... it does not respond. In the ewpesmart app you see the action but after a few seconds it returns to the initial state

**Configuration**
- platform: gree
  name: First AC
  host: 192.168.1.xxx
  port: 7000
  mac: 'xx:xx:xx:xx:xx'
  target_temp_step: 1
  

**Logs**
Logger: homeassistant.core
Source: custom_components/gree/climate.py:276
Integration: Gree A/C ([documentation](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent))
First occurred: 18:16:31 (5 occurrences)
Last logged: 18:20:19

Error executing service: <ServiceCall climate.set_hvac_mode (c:01GH9HFN5G4CRR7X8EM9JVS9VW): entity_id=['climate.first_ac'], hvac_mode=off>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01GH9HJZ0NHKEKFGFPB0W1WSWJ): hvac_mode=off, entity_id=['climate.first_ac']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01GH9HKENZ1QJ56GWBP69DV02A): hvac_mode=off, entity_id=['climate.first_ac']>
Error executing service: <ServiceCall climate.turn_off (c:01GH9HMCMQ2K2PTRD9801XXC23): entity_id=['climate.first_ac']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01GH9HPKZEFPG8619HZCQDRX4M): entity_id=['climate.first_ac'], hvac_mode=off>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 497, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gree/climate.py", line 799, in set_hvac_mode
    self.SyncState({'Pow': 0})
  File "/config/custom_components/gree/climate.py", line 450, in SyncState
    self.SendStateToAc(self._timeout)
  File "/config/custom_components/gree/climate.py", line 276, in SendStateToAc
    data, addr = clientSock.recvfrom(64000)
TimeoutError: timed out

**Comment by tomaskun** [comment]
Any news? I have same problem

**Comment by Rudoxxxx** [comment]
Failed to restart Home Assistant
The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: mapping values are not allowed here in "/config/climate.yaml", line 7, column 28
