### ISSUE TITLE
Upgraded to 2023.6.2 - Gree not loading - Error

### ISSUE THREAD

**Issue by davidgoodman-labsfirst** [RobHofmann/HomeAssistant-GreeClimateComponent#142]
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/gree/climate.py:90
Integration: gree (documentation)
First occurred: 4:38:24 AM (1 occurrences)
Last logged: 4:38:24 AM

Unexpected exception importing platform custom_components.gree.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/gree/climate.py", line 90, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

**Comment by pjanuario** [comment]
I upgraded my installation to this version today and I don't have any errors in my logs.

**Comment by davidgoodman-labsfirst** [comment]
Thanks for responding.
I've tried it 3 times. Perhaps it is my climate setup?

- platform: gree
  name: Living Room AC
  host: 192.168.1.137
  port: 7000
  mac: 'F4:91:1E:F7:22:BB'
  target_temp_step: 1

**Comment by pjanuario** [comment]
> Thanks for responding. I've tried it 3 times. Perhaps it is my climate setup?
> 
> * platform: gree
>   name: Living Room AC
>   host: 192.168.1.137
>   port: 7000
>   mac: 'F4:91:1E:F7:22:BB'
>   target_temp_step: 1

@davidgoodman-labsfirst That might be the reason, yaml configurations are being "unused" or deprecated on most HA components. This was one of the main reasons why I did a fresh install (since the installation had ~3y and mostly automated with yaml configuratins) and I have used gree component UI workflow to configure it worked without issues and had no problems with upgrades so fare. Maybe, the model is different. I would probably try to remove those configurations and the device and configure with UI to understand if the problem persists.

I hope this helps.

**Comment by pjanuario** [comment]
My bad I just noticed that I am actually using the HA core componenent => https://github.com/home-assistant/core/tree/dev/homeassistant/components/gree

**Comment by davidgoodman-labsfirst** [comment]
Hi

Not sure what that means for me.

Should I download a dev module?


________________________________

**Comment by davidgoodman-labsfirst** [comment]
I updated climate.py in my installation from the repo. Thx
