### ISSUE TITLE
cannot import name 'EventStateChangedData' from 'homeassistant.core'

### ISSUE THREAD

**Issue by clipped-osprey** [RobHofmann/HomeAssistant-GreeClimateComponent#159]
Custom component not starting up when previously working fine. Recently updated to 2.8.0 through HACS.

My home assistant log shows this error:
```
2024-05-15 13:46:21.454 ERROR (MainThread) [homeassistant.config] Platform error: climate - cannot import name 'EventStateChangedData' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1437, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1070, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1145, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1133, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1060, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1232, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/gree/climate.py", line 40, in <module>
    from homeassistant.core import Event, EventStateChangedData, callback
ImportError: cannot import name 'EventStateChangedData' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
```

**Configuration**
config.yaml:
```

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

climate: !include climate.yaml

logger:
  default: error
  logs:
    custom_components.gree: debug
    custom_components.gree.climate: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24

homeassistant:
  name: "redacted"
  external_url: "redacted"


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

```

climate.yaml:
```
- platform: gree
  name: Bedroom AC
  host: 192.168.1.197
  port: 7000
  mac: '502CC62D1922'
  target_temp_step: 1
```

**Platform:**
 - Home assistant container
 - Version 2024.4.4

**Comment by toughvj** [comment]
Try update Core to latest version.

**Comment by RobHofmann** [comment]
Yes this is a relatively new feature. Please update your HASS to the latest version or downgrade the custom component :). Closing this for now. Feel free to reopen if there are any further questions.
