### ISSUE TITLE
the integration doesn't add my air conditioner

### ISSUE THREAD

**Issue by Srdiv** [RobHofmann/HomeAssistant-GreeClimateComponent#214]
hello, there are two C&H air conditioners, one works with integration into HA, the other I can’t connect in any way, it’s always unavailable, I changed the encryption_version but it didn’t help. With the Gree Climate integration everything worked fine, but after the latest updates the integration does not work, I wanted to switch to GreeClimateComponent. FW Version 1.23 AC.

**Configuration**
`  - platform: gree
    name: First AC
    host: 192.168.88.24
    port: 7000
    mac: '50:2C:C6:7C:04:D2'
    target_temp_step: 1
    
    
  - platform: gree
    name: second AC
    host: 192.168.88.46
    port: 7000
    mac: '50:2C:C6:DF:BC:A7'
    encryption_version: 2
    target_temp_step: 1 `
`

**Screenshots**
<img width="762" alt="Снимок экрана 2024-10-17 в 00 36 11" src="https://github.com/user-attachments/assets/02c08ebd-13ac-4914-afd5-b3516f17e596">

**Logs**
2024-10-17 00:17:29.713 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gree which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-17 00:17:29.714 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-17 00:17:29.715 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mikrotik_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-17 00:17:29.717 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration better_thermostat which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-17 00:17:29.719 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hikvision_next which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-17 00:17:29.720 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-17 00:17:29.803 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Network Video Recorder' from integration hikvision_next has an invalid unique_id '[['hikvision_next', 'DS-7616NI-K21620211010CCRRG86986734WCVU']]', please create a bug report at https://github.com/maciej-or/hikvision_next/issues
2024-10-17 00:17:44.631 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f945cfa50>,) inside the event loop by custom integration 'hikvision_next' at custom_components/hikvision_next/isapi.py, line 186: hw_info = (await self.isapi.System.deviceInfo(method=GET)).get("DeviceInfo", {}) (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/maciej-or/hikvision_next/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
    await isapi.get_hardware_info()
  File "/config/custom_components/hikvision_next/isapi.py", line 202, in get_hardware_info
    await self.get_device_info()
  File "/config/custom_components/hikvision_next/isapi.py", line 186, in get_device_info
    hw_info = (await self.isapi.System.deviceInfo(method=GET)).get("DeviceInfo", {})

2024-10-17 00:17:49.663 WARNING (MainThread) [homeassistant.components.roborock.coordinator] Using the cloud API for device 4gGXMvKnn5dW9wEpQqo9JH. This is not recommended as it can lead to rate limiting. We recommend making your vacuum accessible by your Home Assistant instance
2024-10-17 00:17:59.803 ERROR (MainThread) [homeassistant.components.homekit] HomeKit HASS Bridge HV cannot startup: entity not available: {'include_domains': [], 'exclude_domains': [], 'include_entities': ['camera.ffmpeg'], 'exclude_entities': [], 'include_entity_globs': [], 'exclude_entity_globs': []}
2024-10-17 00:18:05.056 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed subscribing to service: UpnpConnectionError("UpnpConnectionTimeoutError('TimeoutError()', None)", None)
2024-10-17 00:18:05.061 WARNING (MainThread) [homeassistant.components.dlna_dmr] Failed connecting to recently alive device at http://192.168.88.22:38521/description.xml: UpnpConnectionError("UpnpConnectionTimeoutError('TimeoutError()', None)", None)
2024-10-17 00:18:06.031 WARNING (MainThread) [homeassistant.components.media_player] Updating dlna_dmr media_player took longer than the scheduled update interval 0:00:10
2024-10-17 00:18:06.032 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.dlna_player_mediacenter is taking over 10 seconds
2024-10-17 00:18:16.033 WARNING (MainThread) [homeassistant.components.media_player] Updating dlna_dmr media_player took longer than the scheduled update interval 0:00:10
2024-10-17 00:18:23.056 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed subscribing to service: UpnpConnectionError("UpnpConnectionTimeoutError('TimeoutError()', None)", None)
2024-10-17 00:18:34.525 INFO (MainThread) [custom_components.gree.climate] should_poll()
2024-10-17 00:18:34.527 INFO (SyncWorker_9) [custom_components.gree.climate] update()
2024-10-17 00:18:34.528 INFO (SyncWorker_9) [custom_components.gree.climate] Starting SyncState
2024-10-17 00:18:34.528 INFO (SyncWorker_9) [custom_components.gree.climate] Fetching(192.168.88.24, 7000, 10, {"cid":"app","i":0,"pack":"RE0sGB6OfUoy29WMOJbZdxZq0O/Z+ocIttqD4J1Uhs161zaNOypGq1jT4al1gV9ViKbt1MIokEcv9hLw2dsaL59X7rQpkgO1XY5FR0g/rfQt9n0hvUJEMRXsJFtOe1R3xXD6XSN7IW8IvJ8prOf5QXG/ls14JwcXEM+b2mNCJvAHNL1OL7otBXtkt7pkporVotla4hoHvccJIIx5tjYID03O8B7TsG8Tz/pdMYdfqYFTk8HXSPKHtqW6uTZPscEbvRFEklYUFuyXtVbKcn52aG+6Dee0iEs+nShGQM58DZ1Pdp7F0T5Plk9nWFEQ4p8H","t":"pack","tcid":"502cc67c04d2","uid":0})
2024-10-17 00:18:34.530 INFO (SyncWorker_9) [custom_components.gree.climate] 3
2024-10-17 00:18:34.547 INFO (SyncWorker_9) [custom_components.gree.climate] Setting acOptions with retrieved HVAC values
2024-10-17 00:18:34.547 INFO (SyncWorker_9) [custom_components.gree.climate] Setting Pow: 1
2024-10-17 00:18:34.548 INFO (SyncWorker_9) [custom_components.gree.climate] Setting Mod: 4
2024-10-17 00:18:34.548 INFO (SyncWorker_9) [custom_components.gree.climate] Setting SetTem: 21
2024-10-17 00:18:34.548 INFO (SyncWorker_9) [custom_components.gree.climate] Setting WdSpd: 0
2024-10-17 00:18:34.548 INFO (SyncWorker_9) [custom_components.gree.climate] Setting Air: 0
2024-10-17 00:18:34.548 INFO (SyncWorker_9) [custom_components.gree.climate] Setting Blo: 0
2024-10-17 00:18:34.548 INFO (SyncWorker_9) [custom_components.gree.climate] Setting Health: 1
2024-10-17 00:18:34.548 INFO (SyncWorker_9) [custom_components.gree.climate] Setting SwhSlp: 0
2024-10-17 00:18:34.548 INFO (SyncWorker_9) [custom_components.gree.climate] Setting Lig: 1
2024-10-17 00:18:34.549 INFO (SyncWorker_9) [custom_components.gree.climate] Setting SwingLfRig: 0
2024-10-17 00:18:34.549 INFO (SyncWorker_9) [custom_components.gree.climate] Setting SwUpDn: 0
2024-10-17 00:18:34.549 INFO (SyncWorker_9) [custom_components.gree.climate] Setting Quiet: 0
2024-10-17 00:18:34.549 INFO (SyncWorker_9) [custom_components.gree.climate] Setting Tur: 0
2024-10-17 00:18:34.549 INFO (SyncWorker_9) [custom_components.gree.climate] Setting StHt: 0
2024-10-17 00:18:34.549 INFO (SyncWorker_9) [custom_components.gree.climate] Setting TemUn: 0
2024-10-17 00:18:34.550 INFO (SyncWorker_9) [custom_components.gree.climate] Setting HeatCoolType: 0
2024-10-17 00:18:34.550 INFO (SyncWorker_9) [custom_components.gree.climate] Setting TemRec: 0
2024-10-17 00:18:34.550 INFO (SyncWorker_9) [custom_components.gree.climate] Setting SvSt: 0
2024-10-17 00:18:34.550 INFO (SyncWorker_9) [custom_components.gree.climate] Setting SlpMod: 0
2024-10-17 00:18:34.550 INFO (SyncWorker_9) [custom_components.gree.climate] Setting TemSen: 61
2024-10-17 00:18:34.550 INFO (SyncWorker_9) [custom_components.gree.climate] Done setting acOptions
2024-10-17 00:18:34.551 INFO (SyncWorker_9) [custom_components.gree.climate] HA target temp set according to HVAC state to: 21
2024-10-17 00:18:34.551 INFO (SyncWorker_9) [custom_components.gree.climate] HA lights option set according to HVAC state to: on
2024-10-17 00:18:34.551 INFO (SyncWorker_9) [custom_components.gree.climate] HA xfan option set according to HVAC state to: off
2024-10-17 00:18:34.551 INFO (SyncWorker_9) [custom_components.gree.climate] HA health option set according to HVAC state to: on
2024-10-17 00:18:34.551 INFO (SyncWorker_9) [custom_components.gree.climate] HA powersave option set according to HVAC state to: off
2024-10-17 00:18:34.552 INFO (SyncWorker_9) [custom_components.gree.climate] HA sleep option set according to HVAC state to: off
2024-10-17 00:18:34.552 INFO (SyncWorker_9) [custom_components.gree.climate] HA 8℃ heat option set according to HVAC state to: off
2024-10-17 00:18:34.552 INFO (SyncWorker_9) [custom_components.gree.climate] HA air option set according to HVAC state to: off
2024-10-17 00:18:34.552 INFO (SyncWorker_9) [custom_components.gree.climate] HA operation mode set according to HVAC state to: heat
2024-10-17 00:18:34.552 INFO (SyncWorker_9) [custom_components.gree.climate] HA swing mode set according to HVAC state to: Default
2024-10-17 00:18:34.553 INFO (SyncWorker_9) [custom_components.gree.climate] HA fan mode set according to HVAC state to: Auto
2024-10-17 00:18:34.553 INFO (SyncWorker_9) [custom_components.gree.climate] HA current temperature set with device built-in temperature sensor state : 21.0
2024-10-17 00:18:34.554 INFO (SyncWorker_9) [custom_components.gree.climate] Finished SyncState
2024-10-17 00:18:34.555 INFO (MainThread) [custom_components.gree.climate] supported_features(): 425
2024-10-17 00:18:34.556 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2024-10-17 00:18:34.556 INFO (MainThread) [custom_components.gree.climate] hvac_modes(): [<HVACMode.AUTO: 'auto'>, <HVACMode.COOL: 'cool'>, <HVACMode.DRY: 'dry'>, <HVACMode.FAN_ONLY: 'fan_only'>, <HVACMode.HEAT: 'heat'>, <HVACMode.OFF: 'off'>]
2024-10-17 00:18:34.556 INFO (MainThread) [custom_components.gree.climate] min_temp(): 16
2024-10-17 00:18:34.556 INFO (MainThread) [custom_components.gree.climate] max_temp(): 30
2024-10-17 00:18:34.557 INFO (MainThread) [custom_components.gree.climate] target_temperature_step(): 1.0
2024-10-17 00:18:34.557 INFO (MainThread) [custom_components.gree.climate] fan_list(): ['Auto', 'Low', 'Medium-Low', 'Medium', 'Medium-High', 'High', 'Turbo', 'Quiet']
2024-10-17 00:18:34.557 INFO (MainThread) [custom_components.gree.climate] swing_modes(): ['Default', 'Swing in full range', 'Fixed in the upmost position', 'Fixed in the middle-up position', 'Fixed in the middle position', 'Fixed in the middle-low position', 'Fixed in the lowest position', 'Swing in the downmost region', 'Swing in the middle-low region', 'Swing in the middle region', 'Swing in the middle-up region', 'Swing in the upmost region']
2024-10-17 00:18:34.557 INFO (MainThread) [custom_components.gree.climate] available(): Device is online
2024-10-17 00:18:34.557 INFO (MainThread) [custom_components.gree.climate] hvac_mode(): heat
2024-10-17 00:18:34.558 INFO (MainThread) [custom_components.gree.climate] supported_features(): 425
2024-10-17 00:18:34.558 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2024-10-17 00:18:34.558 INFO (MainThread) [custom_components.gree.climate] current_temperature(): 21.0
2024-10-17 00:18:34.558 INFO (MainThread) [custom_components.gree.climate] target_temperature(): 21
2024-10-17 00:18:34.558 INFO (MainThread) [custom_components.gree.climate] fan_mode(): Auto
2024-10-17 00:18:34.559 INFO (MainThread) [custom_components.gree.climate] swing_mode(): Default
2024-10-17 00:18:34.559 INFO (MainThread) [custom_components.gree.climate] supported_features(): 425
2024-10-17 00:18:34.559 INFO (MainThread) [custom_components.gree.climate] should_poll()
2024-10-17 00:18:34.560 INFO (SyncWorker_20) [custom_components.gree.climate] update()
2024-10-17 00:18:34.560 INFO (SyncWorker_20) [custom_components.gree.climate] Retrieving HVAC encryption key
2024-10-17 00:18:34.561 INFO (SyncWorker_20) [custom_components.gree.climate] Fetching(192.168.88.46, 7000, 10, {"cid": "app","i": 1,"pack": "5PBz8QNvyisjdu/sOjXtGX7qULphBhZHDaCq/lko99Kj9mrs/0p7GUTdWxmNaBUt","t":"pack","tcid":"502cc6dfbca7","uid": 0})
2024-10-17 00:18:34.562 INFO (SyncWorker_20) [custom_components.gree.climate] 3
2024-10-17 00:18:44.561 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.second_ac is taking over 10 seconds
2024-10-17 00:18:44.572 INFO (SyncWorker_20) [custom_components.gree.climate] Error getting device encryption key!
2024-10-17 00:18:44.575 INFO (MainThread) [custom_components.gree.climate] supported_features(): 425
2024-10-17 00:18:44.576 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): °C
2024-10-17 00:18:44.576 INFO (MainThread) [custom_components.gree.climate] hvac_modes(): [<HVACMode.AUTO: 'auto'>, <HVACMode.COOL: 'cool'>, <HVACMode.DRY: 'dry'>, <HVACMode.FAN_ONLY: 'fan_only'>, <HVACMode.HEAT: 'heat'>, <HVACMode.OFF: 'off'>]
2024-10-17 00:18:44.576 INFO (MainThread) [custom_components.gree.climate] min_temp(): 16
2024-10-17 00:18:44.576 INFO (MainThread) [custom_components.gree.climate] max_temp(): 30
2024-10-17 00:18:44.577 INFO (MainThread) [custom_components.gree.climate] target_temperature_step(): 1.0
2024-10-17 00:18:44.577 INFO (MainThread) [custom_components.gree.climate] fan_list(): ['Auto', 'Low', 'Medium-Low', 'Medium', 'Medium-High', 'High', 'Turbo', 'Quiet']
2024-10-17 00:18:44.577 INFO (MainThread) [custom_components.gree.climate] swing_modes(): ['Default', 'Swing in full range', 'Fixed in the upmost position', 'Fixed in the middle-up position', 'Fixed in the middle position', 'Fixed in the middle-low position', 'Fixed in the lowest position', 'Swing in the downmost region', 'Swing in the middle-low region', 'Swing in the middle region', 'Swing in the middle-up region', 'Swing in the upmost region']
2024-10-17 00:18:44.577 INFO (MainThread) [custom_components.gree.climate] available(): Device is offline
2024-10-17 00:18:44.577 INFO (MainThread) [custom_components.gree.climate] name(): second AC
2024-10-17 00:18:44.577 INFO (MainThread) [custom_components.gree.climate] supported_features(): 425

**Comment by Srdiv** [comment]
the problem was solved, since the integration did not work, I used the remote control from the air conditioner, and switched the mode from heating to fan, and after that the integration worked for me, I hope this will help someone. Thanks @RobHofmann  for the integration!

**Comment by rubydesign** [comment]
I just want to confirm this, because to be honest it sounded crazy when i first read it.
But i literally spend days debugging and this did it. And for me it gets more weird.
I had 15 units gone unavailable (out of 20) and when i **switched fan mode** on one, all others came back too!!

I don't want to sound to superstitious here, there is a small chance this has to do with my network settings. 
I had the network where the 15 were switched to vpn and so they were in a different country all of a sudden. That could have caused them to go off-line, at least the gree app warns about the region having to be correct. 
And now i switched the vpn off, so it could have been that. Or a combination.

Anyway thanks @Srdiv for sharing the solution., and @RobHofmann for the integration, PS, i am not seeing the coffee/beer button, i would be happy to buy you one, or two (especially beers, two)

**Comment by kielczu** [comment]
I have the same problem with XE7A-24/HC. I have added two devices succesfully, but the third one is always unavailable.

These are my settings:
- platform: gree
  name: GREE-S1
  host: 192.168.8.221
  port: 7000
  mac: '50:2C:C6:DF:73:21'
  target_temp_step: 1
- platform: gree
  name: GREE-S3
  host: 192.168.8.223
  port: 7000
  mac: 'C0:39:37:0F:E9:A3'
  target_temp_step: 1
  encryption_version: 2
- platform: gree
  name: GREE-S2
  host: 192.168.8.222
  port: 7000
  mac: '94:24:B8:01:7A:44'
  target_temp_step: 1

And the log for GREE-S3 is always:
2024-10-27 14:41:44.590 INFO (MainThread) [custom_components.gree.climate] Setting up Gree climate platform
2024-10-27 14:41:44.590 INFO (MainThread) [custom_components.gree.climate] Adding Gree climate device to hass
2024-10-27 14:41:44.590 INFO (MainThread) [custom_components.gree.climate] Initialize the GREE climate device
2024-10-27 14:41:44.590 INFO (MainThread) [custom_components.gree.climate] name(): GREE-S3
2024-10-27 14:41:44.590 INFO (MainThread) [custom_components.gree.climate] name(): GREE-S3
2024-10-27 14:41:44.591 INFO (MainThread) [custom_components.gree.climate] supported_features(): 425
2024-10-27 14:41:44.591 INFO (MainThread) [custom_components.gree.climate] temperature_unit(): ..C
2024-10-27 14:41:44.591 INFO (MainThread) [custom_components.gree.climate] hvac_modes(): [<HVACMode.AUTO: 'auto'>, <HVACMode.COOL: 'cool'>, <HVACMode.DRY: 'dry'>, <HVACMode.FAN_ONLY: 'fan_only'>, <HVACMode.HEAT: 'heat'>, <HVACMode.OFF: 'off'>]  
2024-10-27 14:41:44.591 INFO (MainThread) [custom_components.gree.climate] min_temp(): 16
2024-10-27 14:41:44.591 INFO (MainThread) [custom_components.gree.climate] max_temp(): 30
2024-10-27 14:41:44.591 INFO (MainThread) [custom_components.gree.climate] target_temperature_step(): 1.0
2024-10-27 14:41:44.591 INFO (MainThread) [custom_components.gree.climate] fan_list(): ['Auto', 'Low', 'Medium-Low', 'Medium', 'Medium-High', 'High', 'Turbo', 'Quiet']
2024-10-27 14:41:44.591 INFO (MainThread) [custom_components.gree.climate] swing_modes(): ['Default', 'Swing in full range', 'Fixed in the upmost position', 'Fixed in the middle-up position', 'Fixed in the middle position', 'Fixed in the middle-
2024-10-27 14:41:44.592 INFO (MainThread) [custom_components.gree.climate] supported_features(): 425
2024-10-27 14:41:44.592 INFO (MainThread) [custom_components.gree.climate] Gree climate device added to hass()
2024-10-27 14:41:44.592 INFO (MainThread) [custom_components.gree.climate] update()
2024-10-27 14:41:44.592 INFO (MainThread) [custom_components.gree.climate] Retrieving HVAC encryption key
2024-10-27 14:41:44.593 INFO (MainThread) [custom_components.gree.climate] Fetching(192.168.8.223, 7000, 10, {"cid": "app","i": 1,"pack": "cF75QLiR1N9+XupJ+VKg4Z3xM9Wmdxq80T4WdlHY+7ej9mrs/0p7GUTdWxmNaBUt","t":"pack","tcid":"c039370fe9a3","uid": 
2024-10-27 14:41:44.593 INFO (MainThread) [custom_components.gree.climate] 3
2024-10-27 14:41:54.604 INFO (MainThread) [custom_components.gree.climate] Error getting device encryption key!

Please assist

**Comment by rubydesign** [comment]
Hi @kielczu  
i just noticed that the one that doesn't work is the one where you have the encryption_version explicitly defined. Have you tried not doing that?
And off course you see the device on the net, ping it ,  maybe try sudo  nmap -n -PN -sT -sU -p 7000 192.168.8.223 (that should report a fileserver)

**Comment by kielczu** [comment]
It disnt work without encryption_version either. I added it as part of troubleshooting with no change in behaviour. I can ping the device like any other. As uou can see in the logs it does respond but the default encryption key HA is trying to use seems incorrect

**Comment by rubydesign** [comment]
@kielczu That error message seems to cover a fair amount of errors, including wrong ip. 
Does the device have access to the network and is not on a vpn ? (it needs to be able to call home, and do so from a consistent country)

And can you check 
`echo -n "{\"t\": \"scan\"}" | nc -u 192.168.8.223 7000`
That should return json, like `{"t":"pack","i":1,"uid":0,"cid":"502c . .....`

**Comment by RobHofmann** [comment]
> @RobHofmann for the integration, PS, i am not seeing the coffee/beer button, i would be happy to buy you one, or two (especially beers, two)

Appreciate the thought man! However i'm not looking for fame or fortune. Just want to share the fun projects I create with the world :). If you really want to donate something, please donate to a charity instead of to me! Again; appreciate the thought!
