### ISSUE TITLE
Error while setting up platform gree when not connected to power line

### ISSUE THREAD

**Issue by jarzebskim** [RobHofmann/HomeAssistant-GreeClimateComponent#45]
My Air Conditioning unit is not connected to power line for a few months every year. when I want I can enable it remotely from HA (via sonoff pow). But there is a problem. When HA was restarted during that time I get "entity not absent" warnings in UI. 

Can You setup unit even is not connected? For example with unknown status or similar? 

Now when I want to power on AC I have to restart Home Assistant to get my entity back. 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 112, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/config/custom_components/gree/climate.py", line 155, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/config/custom_components/gree/climate.py", line 227, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/config/custom_components/gree/climate.py", line 210, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out`

**Comment by RobHofmann** [comment]
Thats not possible, sorry. Thats a limitation on how Home Assistant manages its entities.

Closing this for now. Let me know if you have other input or have questions.
