### ISSUE TITLE
Lack of exception handling during a socket timeout

### ISSUE THREAD

**Issue by srozb** [RobHofmann/HomeAssistant-GreeClimateComponent#53]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see a traceback upon HA startup. This happens every time I restart my HA.

**Describe the solution you'd like**
Putting a `clientSock.recvFrom(64000)` inside a `try except` and log a warning line instead of full traceback.

**Describe alternatives you've considered**
Not logging anything at all, yet handle the exception.

**Additional context**
Full traceback goes here:

```
2020-02-05 21:05:39 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 709, in async_added_to_hass
    self.SyncState()
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 382, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 231, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 210, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
```

**Comment by RobHofmann** [comment]
Personally I prefer to see stacktraces because they mean a lot more to me.

If you receive this issue, make sure to check #40. Im not sure if you have this running normally, but if it doesnt work at all, #40 might be a fix for you.

**Comment by srozb** [comment]
#40 is not related to this issue. I am not having issues with controlling my AC as it works fine, but my logs are flooded with useless tracebacks caused by socket timeouts from time to time. My proposition would be to introduce `socket.timeout` handling here: [climate.py#L220](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/blob/master/custom_components/gree/climate.py#L220).

**Comment by RobHofmann** [comment]
We could make some kind of switch which enables/disables handling it and showing the stacktrace or not.

Im not sure what the best practice would be here. Feel free to make a PR.

**Comment by srozb** [comment]
Anyway, closing for now.
