### ISSUE TITLE
Update for climate.ac fails Traceback

### ISSUE THREAD

**Issue by karkaaa** [RobHofmann/HomeAssistant-GreeClimateComponent#56]
Hello,

a lot of this error in my HA log:

`2020-02-26 22:37:56 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.ac fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gree/climate.py", line 627, in update
    self.SyncState()
  File "/config/custom_components/gree/climate.py", line 410, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/config/custom_components/gree/climate.py", line 241, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/config/custom_components/gree/climate.py", line 220, in FetchResult
    data, addr = clientSock.recvfrom(64000)`

Home Assistant 0.105.5 (docker)
Gree A/C: 2.1.1
HACS: 0.21.6
AC model: GREE GWH18QD

**Comment by ardeus-ua** [comment]
Same thing
Hassio 106.5

**Comment by RobHofmann** [comment]
Please take a look at #40 

This might be the same issue as yours

**Comment by karkaaa** [comment]
I am using MAC wirth ":"

Not same.

**Comment by RobHofmann** [comment]
Yes, but some models require the MAC notation with "-". Did you also try this?

**Comment by karkaaa** [comment]
Not working at all with "-".

**Comment by beadamant** [comment]
Same here
Its connected and I can control AC but keep geeting error
I use “:” Mac
I dont use encryption key
I dont have Andriod phone

**Comment by RobHofmann** [comment]
Closing this. Let me know if any more information arises.
