### ISSUE TITLE
AC is working but keep getting errors

### ISSUE THREAD

**Issue by m-alzahrani** [RobHofmann/HomeAssistant-GreeClimateComponent#61]
I can see the AC in HA and I can control it, everything works fine for me
but I keep getting a lots of error message. and I don't like seeing error in my log 😃 
I have tried ":" and "-" but nothing changed
sometimes it happend in Gree+ app I got network timeout error

YMAL configuration
```
climate:
  - platform: gree
    name: Malak_AC
    host: 192.168.1.6
    port: 7000
    mac: xx:xx:xx:xx:xx:xx
    target_temp_step: 1
    encryption_key: XXXXXXXXXXXXX (got it from iphone gree.sqlite file"
```

````
Logger: homeassistant.helpers.entity
Source: custom_components/gree/climate.py:220
First occurred: 11:59:51 AM (1 occurrences)
Last logged: 11:59:51 AM

Update for climate.malak_ac fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gree/climate.py", line 627, in update
    self.SyncState()
  File "/config/custom_components/gree/climate.py", line 410, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/config/custom_components/gree/climate.py", line 241, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/config/custom_components/gree/climate.py", line 220, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
```

```
Logger: homeassistant.helpers.entity
Source: __main__.py:356
First occurred: 11:59:41 AM (1 occurrences)
Last logged: 11:59:41 AM

Update of climate.malak_ac is taking over 10 seconds
```

**Platform:**
HASSIO
Chrome

**Comment by RobHofmann** [comment]
The message indicates HA can't connect to the AC. I can't see why from here. Try to capture packets to see if you have network issues (dropping packets or something like that).

**Comment by RobHofmann** [comment]
Closing this for now. Feel free to reopen if something pops up.
