### ISSUE TITLE
can not run this component please

### ISSUE THREAD

**Issue by becomecore** [RobHofmann/HomeAssistant-GreeClimateComponent#67]
**Describe the bug**
sorry for my bad english
first,i clean install HA on "termux-ubuntu"on android, HA service is normal.
upload this component to server,and edited the yaml,something goes wrong. 
**To Reproduce**
restart the ha service
so is the log:
`2020-06-19 13:05:57 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-19 13:06:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for gree which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-19 13:06:13 ERROR (MainThread) [homeassistant.components.climate] Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/helpers/entity_platform.py", line 441, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/root/.homeassistant/custom_components/gree/climate.py", line 760, in async_added_to_hass
    self.SyncState()
  File "/root/.homeassistant/custom_components/gree/climate.py", line 410, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/root/.homeassistant/custom_components/gree/climate.py", line 241, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/root/.homeassistant/custom_components/gree/climate.py", line 223, in FetchResult
    pack = receivedJson['pack']
KeyError: 'pack'
`
**Configuration**
Share your YAML here
`# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include climate.yaml

`

`- platform: gree
  name: First AC
  host: 192.168.1.51
  port: 7000
  mac: '37-49-9d-19-00-00-00'
  target_temp_step: 1
  encryption_key: oxp5wq4TrtwJ6ARo
`
**Expected behavior**

**Screenshots**

**Platform:**
 - OS: ubuntu 20.14 on termux on android
 - Browser: chrome
 - Version:current github version

**Additional context**

**Comment by becomecore** [comment]
[home-assistant.log](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/files/4802587/home-assistant.log)

**Comment by RobHofmann** [comment]
```
- platform: gree
  name: First AC
  host: 192.168.1.51
  port: 7000
  mac: '37:49:9d:19:00:00:00'
  target_temp_step: 1
  encryption_key: oxp5wq4TrtwJ6ARo
```

Try it like this. I changed the mac - to :.

**Comment by becomecore** [comment]
changed,and here is the new log.
[home-assistant2.log](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/files/4804635/home-assistant2.log)

**Comment by RobHofmann** [comment]
Hmm this is weird. I dont see what is going wrong or why. I can only think of that your hardware doesnt support the Gree protocol like this implementation (i've seen other implementations of the Gree protocol which are incompatible).

Try enabling debugging in the logs for this component. Maybe that gives us some more information.

Please refer to the the README and follow step 4. Please post the logs after this :).

**Comment by becomecore** [comment]
thanks over all,i will try later~

**Comment by becomecore** [comment]
`Logger: homeassistant.components.climate
Source: custom_components/gree/climate.py:247
Integration: 空调 (documentation, issues)
First occurred: 上午9:56:52 (1 occurrences)
Last logged: 上午9:56:52

Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 449, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 760, in async_added_to_hass
    self.SyncState()
  File "/config/custom_components/gree/climate.py", line 413, in SyncState
    self._acOptions = self.SetAcOptions(self._acOptions, optionsToFetch, currentValues)
  File "/config/custom_components/gree/climate.py", line 247, in SetAcOptions
    _LOGGER.info('Setting %s: %s' % (key, optionValuesToOverride[newOptionsToOverride.index(key)]))
IndexError: list index out of range`

**Comment by becomecore** [comment]
i use  "Gree MC31-00/C2 central air conditioning cloud control multi-connection WiFi" to control  3 ACs. so these 3 ACs have the same ip address.
[home-assistant.log](https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/files/4910248/home-assistant.log)

**Comment by RobHofmann** [comment]
The integration is getting an invalid response (the JSON isn't what the integration expects). I also never tested this on a setup where multiple AC's have the same IP nor am I in the position to test this.

Feel free to modify this integration and make PR supporting this use-case.

**Comment by RobHofmann** [comment]
Closing this since different protocol implementations are not supported by this integration. Feel free to make a PR adding support for your model.
