### ISSUE TITLE
cannot import name 'SUPPORT_TARGET_TEMPERATURE' 

### ISSUE THREAD

**Issue by WeiYang1982** [RobHofmann/HomeAssistant-GreeClimateComponent#7]
Home Assistant release with the issue: 0.89

Last working Home Assistant release (if known): 0.88.1

Operating environment (Hass.io/Docker/Windows/etc.): Docker raspberrypi3-homeassistant

Component/platform: Neato Robotics

Description of problem:

Since the last update of hass I have an issue when it start and the sensors are not present.

Traceback (if applicable):
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/climate/gree.py", line 16, in <module>
    from homeassistant.components.climate import (ClimateDevice, PLATFORM_SCHEMA,
ImportError: cannot import name 'SUPPORT_TARGET_TEMPERATURE'
```

**Comment by leungyuan** [comment]
Yes. Please support 0.89.x +

**Comment by RobHofmann** [comment]
This should be fixed now. Please let me know if you encounter any issues with this.
