### ISSUE TITLE
 Unable to change the State

### ISSUE THREAD

**Issue by cej0t4** [RobHofmann/HomeAssistant-GreeClimateComponent#73]
**Describe the bug**
I cannot change the AC status (temperature, fan ...), with the GREE + app everything works perfectly
If I modify the state from the app, the states are updated in HA.

**Configuration**
climate.yaml
```
- platform: gree
  name: Gree HVAC
  host: 192.168.1.11
  port: 7000
  mac: 'XX:XX:XX:XX:XX:XX'
  target_temp_step: 1
```

**Expected behavior**
Expecting to be able to control the states of my AC through HA

**Platform:**
 - OS: HASSIO
 - Browser: chrome
 - Version: 0.113.1

**Additional context**
I have tried with ":" and "-" on mac, without result

log
```
2020-07-27 20:22:44 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_fan_mode (c:e4dfd9b5499546979d2424df913a62ba): entity_id=['climate.gree_hvac'], fan_mode=medium>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1300, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 422, in async_set_fan_mode
    await self.hass.async_add_executor_job(self.set_fan_mode, fan_mode)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gree/climate.py", line 745, in set_fan_mode
    self.SyncState({'WdSpd': str(self._fan_modes.index(fan)), 'Tur': 0, 'Quiet': 0})
  File "/config/custom_components/gree/climate.py", line 426, in SyncState
    self.SendStateToAc(self._timeout)
  File "/config/custom_components/gree/climate.py", line 266, in SendStateToAc
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
```

**Comment by cej0t4** [comment]
@RobHofmann can take a look at this problem.
Thank you

**Comment by RobHofmann** [comment]
If the state is being fetched correctly, it means the plugin is working. Over the past few months i've noticed that some gree ac's don't implement the protocol according to the standard, which gives issues with this integration.

You might want to fork this repo and try to see what the difference in protocol is. I can't, since I dont have a debug unit (you may always send me one :))

**Comment by cej0t4** [comment]
Thanks for your time @RobHofmann . How can I debug and send you the information?

**Comment by RobHofmann** [comment]
I would need the hardware to fiddle around with it. It's going to be a lot of going back and forth and testing a lot.

As I said, you or someone else with the same hardware, who knows how to write python could fork this repo and make a fitting solution. I'll close this for now as different (custom gree) protocols are not supported by this integration.
