### ISSUE TITLE
Integration is not working on hass 0.113.3

### ISSUE THREAD

**Issue by Nunak** [RobHofmann/HomeAssistant-GreeClimateComponent#77]
**Describe the bug**
After upgrade to latest hass integration is not working - gui is showing "entity is not available".

**To Reproduce**
Just restart with new version
Log:
2020-08-03 12:26:27 ERROR (MainThread) [homeassistant.components.climate] Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 115, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, eightdegheat_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 160, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 237, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 220, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out

2020-08-03 12:27:42 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.klimatizace_kuchyn fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
    self.update  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 627, in update
    self.SyncState()
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 410, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 241, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/home/homeassistant/.homeassistant/custom_components/gree/climate.py", line 220, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out

**Configuration**
  - platform: gree
    name: Klimatizace kuchyn
    host: 192.168.1.103
    port: 7000
    mac: 'F4:91:1E:D4:14:EE'
    target_temp_step: 1
    lights: input_boolean.klimatizace_obyvak_lights
    xfan: input_boolean.klimatizace_obyvak_xfan
    health: input_boolean.klimatizace_obyvak_health
    sleep: input_boolean.klimatizace_obyvak_sleep
    powersave: input_boolean.klimatizace_obyvak_powersave

**Expected behavior**
Will work :)

**Screenshots**
N/A

**Platform:**
 - OS: debian
 - Browser chrome
 - Version 0.113.3

**Additional context**

**Comment by RobHofmann** [comment]
Do you have the latest version of this integration from HACS? I'm running this integration on 0.113.3 without any issues.

**Comment by RobHofmann** [comment]
PS. It might be this issue: https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/issues/75

**Comment by Nunak** [comment]
> Do you have the latest version of this integration from HACS? I'm running this integration on 0.113.3 without any issues.

Yes I have, no update in HACS is showing to me.


> PS. It might be this issue: #75

Let me check more, but I does not have problem with resolving this FQDN.

This problem I saw first time when I did upgrade on 0.113.3. I am not a programer but looks like some timeout is more strict than it was with this new version.

**Comment by realthk** [comment]
The reason you have the problem right now is that Gree server went down for good a few days ago.
I'm still on 0.113.2 and having the same issue, but used to have it with much older versions long ago also, just I did not know the reason back then and suspected wi-fi issues (and the server probably was down only for short times, not for days like now)
So it has nothing to do with HA version, nor this custom component.
Disabling net access completely for the Gree AC hopefully might solve the problem.

**Comment by Al4x** [comment]
For some reason, the AC is trying to reach the Gree server and if it's not reached, the wi-fi module goes in standby.
I found that if I ping the local AC IP address while restarting the HA server, resolves the connection problem.

**Comment by Nunak** [comment]
> For some reason, the AC is trying to reach the Gree server and if it's not reached, the wi-fi module goes in standby.
> I found that if I ping the local AC IP address while restarting the HA server, resolves the connection problem.

Yes I can confirm this. Thanks for this info!

**Comment by Nunak** [comment]
This could be closed. Problem is related to down Gree server.
