### ISSUE TITLE
Commands don't work

### ISSUE THREAD

**Issue by Cusu95** [RobHofmann/HomeAssistant-GreeClimateComponent#80]
**Describe the bug**
Home Assistant can see the ac, its state, temperature etc..but when I try to do something, such as change temperature or turn it on/off, nothing happens.

**Configuration**
- platform: gree
  name: salotto
  host: x.x.x.x
  port: 7000
  mac: '<xx:xx:xx:xx:xx:06>'
  target_temp_step: 1
  encryption_key: g7Ij0Lm3Op6Rs9Uv
  temp_sensor: sensor.ap_living_temp
  health: input_boolean.salotto_health
  sleep: input_boolean.salotto_sleep
  eightdegheat: input_boolean.salotto_eightdegheat
  lights: input_boolean.salotto_lights
  xfan: input_boolean.salotto_xfan
  powersave: input_boolean.salotto_powersave

**Error**
2020-08-18 21:22:25 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_hvac_mode (c:200cdd34e18811eaa6bb5f5f0a013380): entity_id=['climate.salotto'], hvac_mode=off>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1324, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 430, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gree/climate.py", line 752, in set_hvac_mode
    self.SyncState({'Pow': 0})
  File "/config/custom_components/gree/climate.py", line 426, in SyncState
    self.SendStateToAc(self._timeout)
  File "/config/custom_components/gree/climate.py", line 266, in SendStateToAc
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out

**Platform:**
 - OS: HASSIO on Docker
 - Version 0.114

**Comment by Cusu95** [comment]
I solved by adding uid: 0
After this, everything works fine
