### ISSUE TITLE
Cant communicate with the device

### ISSUE THREAD

**Issue by hirani89** [RobHofmann/HomeAssistant-GreeClimateComponent#86]
**Describe the bug**
Error socket timed out.

**To Reproduce**
Added the component on a fresh install of HASS and HACS

**Configuration**
- platform: gree
  name: First AC
  host: 192.168.2.3
  port: 7000
  mac: f4-91-1e-3f-52-da
  target_temp_step: 1
  encryption_key: xxxxxxxxxxxxxx

**Expected behavior**
Not really sure what should happed. 
Would be helpful if the Readme had some screenscots.

**Screenshots**
Logs below
 
**Platform:**
 - OS: HASSOS 4.13
 - Browser: Chrome
 - Version: 0.115.3

**Additional context**

```
2020-09-26 23:15:27 INFO (MainThread) [custom_components.gree.climate] Setting up Gree climate platform
2020-09-26 23:15:27 INFO (MainThread) [custom_components.gree.climate] Adding Gree climate device to hass
2020-09-26 23:15:27 INFO (MainThread) [custom_components.gree.climate] Initialize the GREE climate device
2020-09-26 23:15:27 INFO (MainThread) [custom_components.gree.climate] Using configured encryption key: xxxxxxxxxxxxxxx
2020-09-26 23:15:28 INFO (MainThread) [custom_components.gree.climate] name(): First AC
2020-09-26 23:15:28 INFO (MainThread) [custom_components.gree.climate] Gree climate device added to hass()
2020-09-26 23:15:28 INFO (MainThread) [custom_components.gree.climate] Starting SyncState
2020-09-26 23:15:28 INFO (MainThread) [custom_components.gree.climate] Fetching(192.168.2.3, 7000, 10, {"cid":"app","i":0,"pack":"9MH5htCmz3aI7RBK33LZhcO9+R1aAxXhIYJuj9jOMZjgfU3J+x8MfuhgFi9EzY9HLjDR86z3OKIdA66otB8rjVfp28N4v5xKN4GBRgJLfMZKLp9yYBUnSqKkwPbJaGCk/GNT/OMA7KbDAL05pHrTt51YjKh61dCpBnE0iZMCY9a1qKOHP1sCv8so1QyQB4+a+xUy9YyQl3tkQPmRINWudRZVrYl2RfB5ewtJWk4gB6lqEAS/uuXGKNOkK1AK8R1FnzKinJaW83fZMuAQ/uKNrJdX49Z6Ddu4SHMQeu7hBNc=","t":"pack","tcid":"f4-91-1e-3f-52-da","uid":0})
2020-09-26 23:15:38 ERROR (MainThread) [homeassistant.components.climate] Error while setting up gree platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 807, in async_added_to_hass
    self.SyncState()
  File "/config/custom_components/gree/climate.py", line 434, in SyncState
    currentValues = self.GreeGetValues(optionsToFetch)
  File "/config/custom_components/gree/climate.py", line 251, in GreeGetValues
    return self.FetchResult(self.CIPHER, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['dat']
  File "/config/custom_components/gree/climate.py", line 230, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
2020-09-26 23:15:40 ERROR (MainThread) [homeassistant.components.sensor] syncthru: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 346, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 469, in async_device_update
    await self.async_update()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/syncthru/sensor.py", line 157, in async_update
    self._state = SYNCTHRU_STATE_HUMAN[self.syncthru.device_status()]
KeyError: <SyncthruState.TESTING: 4>
```

**Comment by RobHofmann** [comment]
If it doesnt work alltogether, this error usually means theres a configuration error (there is nothing listening on the defined endpoint).

Also: are you sure your HVAC is listening on port 7000?

**Comment by hirani89** [comment]
Yes, the HVAC is connected properly and communicating on port 7000. I have used  `echo -n "{\"psw\": \"YOUR_WIFI_PASSWORD\",\"ssid\": \"YOUR_WIFI_SSID\",\"t\": \"wlan\"}" | nc -cu 192.168.1.1 7000
` to connect it and my router shows that it's connected.
I also have used it with `https://github.com/arthurkrupa/gree-hvac-mqtt-bridge` before and it worked.

**Comment by RobHofmann** [comment]
Hmm, you could try to replace the -'s in your MAC with : . I've seen some installations where this worked.

Other than that the configuration looks perfectly fine, I can't think of any reason it wouldn't connect using that config.

**Comment by hirani89** [comment]
I've tried both `:` and `-` without any luck. Planning to reset the HVAC and reconnecting again just in case. Will report the outcome.

**Comment by hirani89** [comment]
All good now. Multiple  issues. There was a firewall rule blocking some connections from HASS to the HVAC. After resetting the HVAC, all worked fine. 

I am a beginner in the HASS world. And it was hard for me to figure out the steps to get this working even after successful connection to the HVAC. I kept refreshing the home screen hoping to see some kind of UI to control the HVAC. After a lot of looking around, I figured I had to add a climate card and link this component to get it all working. Could you add this to the documentation for newbs like us.

Thanks

**Comment by hirani89** [comment]
Also, when can we expect horizontal swing. HASS climate now supports it apparently. https://developers.home-assistant.io/docs/core/entity/climate/#swing-modes

**Comment by RobHofmann** [comment]
You don't need the climate card to get it working though. Thats the frontend side of things. You can always use the "dev-tools" and then use the "services" tab to communicate with the HVAC. I'd rather keep this integration clean in the form of the integration itself (so no "How to use on a daily basis" if you catch my drift).

Also feel free to make a pullrequest with the needed changes for horizontal swing, I'm very short on time and don't see this implemented by myself in the near future.

**Comment by manouallou** [comment]
Hi there,

Is the encryption key necessary or optional for this to work? It is a bit too technical for me to extract it but I will try more if it is necessary. My AC is a Toyotomi branded one but it is a Gree inside. 

Here is what I have in my climate.yaml

```
-platform: gree
  name: Toyotomi AC
  host: 192.168.0.111
  port: 7000
  mac: 'XX:XX:XX:XX:XX:XX' (hidden)
  target_temp_step: 1

```
And this is the error from the log:

```
Logger: homeassistant.components.climate

Source: custom_components/gree/climate.py:230
Integration: Climate (documentation, issues)
First occurred: 1:53:51 AM (1 occurrences)
Last logged: 1:53:51 AM
Error while setting up gree platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 118, in async_setup_platform
    GreeClimate(hass, name, ip_addr, port, mac_addr, timeout, target_temp_step, temp_sensor_entity_id, lights_entity_id, xfan_entity_id, health_entity_id, powersave_entity_id, sleep_entity_id, eightdegheat_entity_id, air_entity_id, hvac_modes, fan_modes, swing_modes, encryption_key, uid)
  File "/config/custom_components/gree/climate.py", line 165, in __init__
    self._encryption_key = self.GetDeviceKey().encode("utf8")
  File "/config/custom_components/gree/climate.py", line 247, in GetDeviceKey
    return self.FetchResult(cipher, self._ip_addr, self._port, self._timeout, jsonPayloadToSend)['key']
  File "/config/custom_components/gree/climate.py", line 230, in FetchResult
    data, addr = clientSock.recvfrom(64000)
socket.timeout: timed out
```

**Comment by RobHofmann** [comment]
It is optional. I dont use it for my 3 HVAC's.

My guess would be that something is blocking the communication between HASS & the HVAC.

`socket.timeout: timed out` just simply means there is nothing listening on the defined address (so either it really doesnt listen or the communication gets blocked).

**Comment by manouallou** [comment]
> 
> 
> It is optional. I dont use it for my 3 HVAC's.
> 
> My guess would be that something is blocking the communication between HASS & the HVAC.
> 
> `socket.timeout: timed out` just simply means there is nothing listening on the defined address (so either it really doesnt listen or the communication gets blocked).

Hi @RobHofmann ,

Thank you for your answer. I will just have to try and see if the 7000 port is blocked in my network or try to create a rule and open the port for communication.

I will update you on the results. 

Thank you

**Comment by hirani89** [comment]
To get the device ID, I used Arthur Krupa's Code. [https://github.com/arthurkrupa/gree-hvac-mqtt-bridge](url)

Add `console.log('Device Key: ' + key);` on line 121 in `/app/deviceFactory.js`
<img width="547" alt="Screen Shot 2020-10-02 at 9 46 24 pm" src="https://user-images.githubusercontent.com/2254906/94920099-f5f7f280-04f8-11eb-9694-43ac8b2fcd91.png">

**Comment by manouallou** [comment]
> > It is optional. I dont use it for my 3 HVAC's.
> > My guess would be that something is blocking the communication between HASS & the HVAC.
> > `socket.timeout: timed out` just simply means there is nothing listening on the defined address (so either it really doesnt listen or the communication gets blocked).
> 
> Hi @RobHofmann ,
> 
> Thank you for your answer. I will just have to try and see if the 7000 port is blocked in my network or try to create a rule and open the port for communication.
> 
> I will update you on the results.
> 
> Thank you

Hi, I just wanted to let you know that the integration is working flawlessly without any special configuration or troubleshooting. 

I am almost embarrassed to say that my problem was that the IP of my AC  in the climate.yaml file was wrong (192.168.0.111 instead of 192.168.0.110).

After that everything showed up in HA and I am able to control it fully. 

Thanks Mr. Rob!

**Comment by RobHofmann** [comment]
> > > It is optional. I dont use it for my 3 HVAC's.
> > > My guess would be that something is blocking the communication between HASS & the HVAC.
> > > `socket.timeout: timed out` just simply means there is nothing listening on the defined address (so either it really doesnt listen or the communication gets blocked).
> > 
> > 
> > Hi @RobHofmann ,
> > Thank you for your answer. I will just have to try and see if the 7000 port is blocked in my network or try to create a rule and open the port for communication.
> > I will update you on the results.
> > Thank you
> 
> Hi, I just wanted to let you know that the integration is working flawlessly without any special configuration or troubleshooting.
> 
> I am almost embarrassed to say that my problem was that the IP of my AC in the climate.yaml file was wrong (192.168.0.111 instead of 192.168.0.110).
> 
> After that everything showed up in HA and I am able to control it fully.
> 
> Thanks Mr. Rob!

Haha no problem! I'm glad it all worked out for you! Enjoy!

**Comment by RobHofmann** [comment]
Closing this issue for now. Feel free to re-open if needed.
