### ISSUE TITLE
Gree Heater cannot connect HA 

### ISSUE THREAD

**Issue by yuaner66** [RobHofmann/HomeAssistant-GreeClimateComponent#92]
**Describe the bug**
I bought a Heater of gree NBDF-X6022B [(https://item.taobao.com/item.htm?id=605413577864)](https://item.taobao.com/item.htm?id=605413577864) last year,it  cannot connect HA 

**Configuration**
climate:
  - platform: gree
    name: First AC
    host: 192.168.88.145
    port: 7000
    mac: 'f4:91:1e:bc:d8:4f'
    target_temp_step: 1
    encryption_key: **

**Logs**
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Setting up Gree climate platform
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Adding Gree climate device to hass
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Initialize the GREE climate device
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Using configured encryption key: **
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] name(): First AC
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Gree climate device added to hass()
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Starting SyncState
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Fetching(192.168.88.145, 7000, 10, {"cid":"app","i":0,"pack":"tpEId5bfybs7Jx94MH2YfD4QEq9mMqxGjlsLfbtoyUw8FrRUK4ALhKianWChlnx92XfB1mnjD/d2djAQiAioYgZhVEMqI7OtT/NCJKbq1IMo7yRNaDqW3QCGDVMoVhwBiVdQxgLtNPx4E0hhralQPFbLQ9sC35kE90/GTLdtdNwRW/urCKy8cEBQ2QO+hA657gtJ9dTNtLPtMVBhwM8O8etP2pHXLYlz1LA4Pl6H2Cw2E+wbADvFcEb07YFErLKJK2FqlGfwLmBwOjGOwTfGPc3HUy0cnCR8iLItrhvIzXM=","t":"pack","tcid":"f4911ebcd84f","uid":0})
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Setting acOptions with retrieved HVAC values
2021-01-05 21:18:04 INFO (MainThread) [custom_components.gree.climate] Setting Pow: 1
2021-01-05 21:18:04 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform gree
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/gree/climate.py", line 807, in async_added_to_hass
    self.SyncState()
  File "/config/custom_components/gree/climate.py", line 437, in SyncState
    self._acOptions = self.SetAcOptions(self._acOptions, optionsToFetch, currentValues)
  File "/config/custom_components/gree/climate.py", line 257, in SetAcOptions
    _LOGGER.info('Setting %s: %s' % (key, optionValuesToOverride[newOptionsToOverride.index(key)]))
IndexError: list index out of range

Screenshot on the Gree+ app
![](https://user-images.githubusercontent.com/4413197/103655386-1fb23100-4fa2-11eb-94db-f5e5b413d919.jpg)

**Comment by RobHofmann** [comment]
i'm unable to check this due to not having this piece of hardware. I hope other users with this piece of hardware can help you out. 

Let me know if you find a solution.

**Comment by jodewee** [comment]
Hi, i have the same issue,
did you make any progress on this one?
